grammar Maps
  map     <-  CBo PAIR (COMMA PAIR)* CBc %make_map
  PAIR    <-  string KVs value %make_pair
  value   <-  list / number / string / map
  string  <-  '"' [^"]* '"' _ %make_string
  list    <-  SBo value ("," _ value)* SBc %make_list
  number  <-  [+-]? [0-9]+ ("." [0-9]*)? ("e" [+-]? [0-9]+)? _ %make_number
  KVs     <-  ":" _
  CBo     <-  "{" _
  CBc     <-  "}" _
  SBo     <-  "[" _
  SBc     <-  "]" _
  COMMA   <-  "," _
  _       <-  [ \t\r\n]*

