load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "flexi_cfg_hdrs",
    hdrs = glob(["flexi_cfg/**/*.h"]),
    include_prefix = "flexi_cfg",
    visibility = ["//visibility:public"],
)
